### ISSUE TITLE
GetString issue

### ISSUE THREAD

**Issue by martin211** [martin211/aimp_dotnet#1]
Application: AIMP3.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
Stack:
   at AIMP.AimpObjectExtension.GetString(AIMP36SDK.IAIMPPropertyList*, Int32)
   at AIMP.PlayList.AimpFileInfo.get_Artist()
   at AIMP.DiskCover.TrackInfo..ctor(AIMP.SDK.Interfaces.IAimpPlayer)
   at AIMP.DiskCover.CoverFinderManager.LoadImageWorkItem(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by martin211** [comment]
Fixed
